#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
import logging
from app.model import konfig_objekt

from PyQt4 import QtGui
from app.control import controler

class Validacija():
    def __init__(self):

        self.konfig = konfig_objekt.MainKonfig('konfig_params.cfg')
        self.grafKonfig = konfig_objekt.GrafKonfig('graf_params.cfg')
        self.setup_logging()

    def run(self, argv):
        app = QtGui.QApplication(argv)
        runner = controler.Kontroler(self.konfig, self.grafKonfig)
        sys.exit(app.exec_())

    def setup_logging(self):
        """Inicijalizacija loggera"""
        try:
            logging.basicConfig(level=self.konfig.logLvl,
                                filename=self.konfig.logFile,
                                filemode=self.konfig.logMode,
                                format='{levelname}:::{asctime}:::{module}:::{funcName}:::LOC:{lineno}:::{message}',
                                style='{')
        except Exception as err:
            print('Pogreska prilikom konfiguracije loggera.')
            print(str(err))
            raise SystemExit('Kriticna greska, izlaz iz aplikacije.')

if __name__ == '__main__':
    v = Validacija()
    v.run(sys.argv)

    # TODO! ldl ne valja...limiti ovise o dosta toga..LDL limit treba postaviti skupa sa korekcijom
    # TODO! svaki model mora izvaditi kada korekcija je manja od ldl...vspans...
